### ISSUE TITLE
varchar tasks

### ISSUE THREAD

**Issue by bluestreak01** [questdb/questdb#4360]
**MUST HAVE**
- [x] Run ingestion benchmark with varchar
- [x] Run Clickbench with varchar instead of String
- [x] plan to switch users over to VARCHAR
- [x] Documentation: Documentation should be changed to prefer VARCHAR over STRING at all places.  
- [x] Web console support. @jerrinot: https://github.com/questdb/ui/pull/281
- [x] TextImport deals incorrectly with quotes when importing into a VarChar column @jerrinot https://github.com/questdb/questdb/pull/4476

**NICE TO HAVE**
- [ ] JIT support for varchar_col equals, substring equals, starts with, regexp (this might be moved to MUST HAVE, depending on benchmarking)
- [ ] add varchar variants of io.questdb.griffin.engine.functions.regex SQL functions
- [ ] `to_uppercase(varchar)` currently produces a string. this is unexpected. not sure if this is a blocker. 
- [x] web console to understand rnd_varchar(): @jerrinot https://github.com/questdb/sql-grammar/pull/34
- [ ] Varchar equivalent of [`RndStrRndListFunctionFactory`](https://github.com/questdb/questdb/blob/9683d03251aa6284bf8d2de0d6d60884a477d893/core/src/main/java/io/questdb/griffin/engine/functions/rnd/RndStrRndListFunctionFactory.java#L40)

**COMPLETED**
- [x] add varchar variants of SQL functions: quote_ident, split_part @nwoolmer https://github.com/questdb/questdb/issues/4360
- [x] Validate out of the box behaviour for all protocols: REST, PgWire, ILP. ILP should create VARCHAR columns by default + compatibility flag to revert back to STRING. @jerrinot https://github.com/questdb/questdb/pull/4475
- [x] `alter table alter column type` @ideoma #4413
- [x] support for VARCHAR in WhereClauseParser (timestamp search by VARCHAR) ~@jerrinot~ ~@bluestreak01~ @jerrinot https://github.com/questdb/questdb/pull/4403  
- [x] `AbstractTextLexer` doesn't calculate ASCII flag, so all inserted varchars have `us.isAscii() == false`. We need to fix that @bluestreak01 in https://github.com/questdb/questdb/pull/4401
- [x] varchar update bug @puzpuzpuz #4353

```sql
create table xyz as (select rnd_str(2,5,1) a, timestamp_sequence(0, 1000) ts from long_sequence(10000)) timestamp(ts) partition by DAY;
alter table xyz add column b varchar;
update xyz set b = a;

select count(*) from xyz where a is not null;
select count(*) from xyz where b is not null;
```
- [x] support in InTimestampTimestampFunctionFactory @jerrinot  https://github.com/questdb/questdb/pull/4415
- [x] add varchar variants of str aggregate functions such as min/max
- [x] JIT support for varchar_col IS NULL/IS NOT NULL @puzpuzpuz #4357
- [x] cast varchar to geohashes @mtopolnik
- [x] cast varchar to ipv4 ~@jerrinot~ @mtopolnik
- [x] string vs varchar consistency when casting to timestamp @jerrinot https://github.com/questdb/questdb/pull/4408
- [x] add varchar variants of SQL functions: trim, ltrim, rtrim, strpos, position, replace @mtopolnik  #4430
- [x] add varchar variant of SQL function: starts_with @mtopolnik https://github.com/questdb/questdb/pull/4453
- [x] introduce single varchar key unordered map; the map can leverage stable pointers infra introduced recently to avoid copying varchars into map memory - instead it'll be storing pointers to mmapped memory @jerrinot  https://github.com/questdb/questdb/pull/4435
- [x] Unify access to VARCHAR column, whether inlined or split, in a single class. @mtopolnik https://github.com/questdb/questdb/pull/4453
- [x] `length(varchar)` is dog-slow: we should calculate the raw size - number of continuation bytes instead of doing proper UTF-8 parsing; ideally that should be done with SWAR @mtopolnik #4442
